
# Uses compliant contact
'name': 'tactile_camera'
'is_body_camera': True
'actor_name': 'gelsight_finger'
'attach_link_name': 'elastomer_tip'
'width': 320
'height': 240
# 'image_type': 'rgb',
'image_type': 'depth'
'camera_dist': 0.01037  # my tip
'cx': 0.0109   # 0.02525/2  usually elastomer width divided by 2
'cy': 0.007565   # 0.02075/2  usually elastomer height divided by 2
'near_plane': 0.0001   # distance from the camera point to the near clipping plane in world units (meters)
'tip_to_cam_euler': [0, -2.1748, 0.0]   # camera orientation in attach link frame  0, -1.5707963267948966, 0
'use_collision_geometry': False